INSERT INTO restaurant (name, kitchen, address, info) VALUES ('Enzos', 'Italienisch', 'Musterstadt', 'Platzhaltertext zum Platzhalten für Text');

INSERT INTO tabl (pax, rest_id) VALUES ('4', (SELECT id FROM restaurant WHERE id = '1'));

INSERT INTO user (last_name, first_name, email, password) VALUES('Adams', 'Roy', 'radams1v@xinhuanet.com', '9823');
INSERT INTO user (last_name, first_name, email, password) VALUES('Adams', 'Martin', 'madams2b@msu.edu', '9813');
INSERT INTO user (last_name, first_name, email, password) VALUES('Alvarez', 'Roger', 'ralvarezk@blogs.com', '6105');
INSERT INTO user (last_name, first_name, email, password) VALUES('Alvarez', 'Anne', 'aalvarez1y@mlb.com', '7237');
INSERT INTO user (last_name, first_name, email, password) VALUES('Alvarez', 'Ann', 'aalvarez20@jalbum.net', '2327');
INSERT INTO user (last_name, first_name, email, password) VALUES('Anderson', 'Betty', 'banderson14@digg.com', '0405');
INSERT INTO user (last_name, first_name, email, password) VALUES('Anderson', 'Laura', 'landerson24@icio.us', '6409');
INSERT INTO user (last_name, first_name, email, password) VALUES('Armstrong', 'Christopher', 'carmstrong2p@cyberchimps.com', '3757');
INSERT INTO user (last_name, first_name, email, password) VALUES('Bell', 'David', 'dbell2l@wp.com', '4547');
INSERT INTO user (last_name, first_name, email, password) VALUES('Berry', 'Paula', 'pberry1z@admin.ch', '7745');
INSERT INTO user (last_name, first_name, email, password) VALUES('Bishop', 'Dennis', 'dbishopo@xinhuanet.com', '3543');
INSERT INTO user (last_name, first_name, email, password) VALUES('Bishop', 'Carolyn', 'cbishopw@1688.com', 'E5690');
INSERT INTO user (last_name, first_name, email, password) VALUES('Black', 'Harold', 'hblack2p@clickbank.net', '3343');
INSERT INTO user (last_name, first_name, email, password) VALUES('Bowman', 'Jerry', 'jbowman1j@fotki.com', '8585');
INSERT INTO user (last_name, first_name, email, password) VALUES('Bradley', 'Keith', 'kbradley1c@techcrunch.com', '5353');
INSERT INTO user (last_name, first_name, email, password) VALUES('Brooks', 'Samuel', 'sbrooks4@google.co.uk', '0437');
INSERT INTO user (last_name, first_name, email, password) VALUES('Bryant', 'Donald', 'dbryant1@cdbaby.com', '0019');
INSERT INTO user (last_name, first_name, email, password) VALUES('Burke', 'Tammy', 'tburke2a@theglobeandmail.com', '1619');
INSERT INTO user (last_name, first_name, email, password) VALUES('Burns', 'Joe', 'jburns18@mail.ru', '7455');
INSERT INTO user (last_name, first_name, email, password) VALUES('Campbell', 'Jessica', 'jcampbell2i@cpanel.net', '2177');
INSERT INTO user (last_name, first_name, email, password) VALUES('Campbell', 'Christopher', 'ccampbell2i@amazon.de', '4811');
INSERT INTO user (last_name, first_name, email, password) VALUES('Carpenter', 'Pamela', 'pcarpenterj@china.com.cn', '2465');
INSERT INTO user (last_name, first_name, email, password) VALUES('Carpenter', 'Paul', 'pcarpenter28@dropbox.com', '7094');
INSERT INTO user (last_name, first_name, email, password) VALUES('Carter', 'Tammy', 'tcarter1j@washington.edu', '7002');
INSERT INTO user (last_name, first_name, email, password) VALUES('Carter', 'Paul', 'pcarter1z@cnet.com', '1783');
INSERT INTO user (last_name, first_name, email, password) VALUES('Chapman', 'Justin', 'jchapmans@aol.com', '0295');
INSERT INTO user (last_name, first_name, email, password) VALUES('Chapman', 'Margaret', 'mchapmanb@hud.gov', '9996');
INSERT INTO user (last_name, first_name, email, password) VALUES('Clark', 'Bonnie', 'bclark6@bing.com', '6248');
INSERT INTO user (last_name, first_name, email, password) VALUES('Clark', 'Andrea', 'aclark2j@sphinn.com', '9494');
INSERT INTO user (last_name, first_name, email, password) VALUES('Coleman', 'Shirley', 'scoleman26@bizjournals.com', '1459');
INSERT INTO user (last_name, first_name, email, password) VALUES('Coleman', 'Angela', 'acoleman6@gmpg.org', '5551');
INSERT INTO user (last_name, first_name, email, password) VALUES('Cox', 'Harold', 'hcox23@dyndns.org', '3202');
INSERT INTO user (last_name, first_name, email, password) VALUES('Cruz', 'Alan', 'acruzj@marketwatch.com', '0308');
INSERT INTO user (last_name, first_name, email, password) VALUES('Cunningham', 'Anna', 'acunningham2@yale.edu', '5961');
INSERT INTO user (last_name, first_name, email, password) VALUES('Daniels', 'Robin', 'rdaniels2d@weebly.com', '5902');
INSERT INTO user (last_name, first_name, email, password) VALUES('Daniels', 'Phillip', 'pdaniels1y@hexun.com', '9304');
INSERT INTO user (last_name, first_name, email, password) VALUES('Davis', 'Thomas', 'tdavis1h@globo.com', '9695');
INSERT INTO user (last_name, first_name, email, password) VALUES('Dean', 'Joe', 'jdeanp@vinaora.com', '9705');
INSERT INTO user (last_name, first_name, email, password) VALUES('Dean', 'Sara', 'sdean1t@unc.edu', '7117');
INSERT INTO user (last_name, first_name, email, password) VALUES('Dixon', 'Patricia', 'pdixon2m@biglobe.ne.jp', '4102');
INSERT INTO user (last_name, first_name, email, password) VALUES('Dixon', 'Cynthia', 'cdixon1e@vimeo.com', '7084');
INSERT INTO user (last_name, first_name, email, password) VALUES('Dixon', 'Todd', 'tdixon2o@ed.gov', '9657');
INSERT INTO user (last_name, first_name, email, password) VALUES('Elliott', 'David', 'delliottn@wsj.com', '5138');
INSERT INTO user (last_name, first_name, email, password) VALUES('Elliott', 'Gregory', 'gelliott2f@exblog.jp', '5278');
INSERT INTO user (last_name, first_name, email, password) VALUES('Ellis', 'James', 'jellisa@wordpress.com', '0365');
INSERT INTO user (last_name, first_name, email, password) VALUES('Ferguson', 'Russell', 'rferguson1b@uol.com.br', '8970');
INSERT INTO user (last_name, first_name, email, password) VALUES('Ferguson', 'Mark', 'mferguson2m@columbia.edu', '0162');
INSERT INTO user (last_name, first_name, email, password) VALUES('Fields', 'Lori', 'lfieldsq@smh.com.au', '4243');
INSERT INTO user (last_name, first_name, email, password) VALUES('Fisher', 'Thomas', 'tfisher26@sina.com.cn', '0935');
INSERT INTO user (last_name, first_name, email, password) VALUES('Ford', 'Matthew', 'mfordi@ucoz.com', 'E9676');
INSERT INTO user (last_name, first_name, email, password) VALUES('Fowler', 'Clarence', 'cfowler1t@unicef.org', '2234');
INSERT INTO user (last_name, first_name, email, password) VALUES('Fowler', 'Steve', 'sfowler2f@ed.gov', '9290');
INSERT INTO user (last_name, first_name, email, password) VALUES('Fox', 'Craig', 'cfox1v@sakura.ne.jp', '1524');
INSERT INTO user (last_name, first_name, email, password) VALUES('Freeman', 'Kimberly', 'kfreemank@cmu.edu', '9766');
INSERT INTO user (last_name, first_name, email, password) VALUES('Freeman', 'Johnny', 'jfreeman1g@aboutads.info', '7764');
INSERT INTO user (last_name, first_name, email, password) VALUES('Garza', 'Carl', 'cgarzal@friendfeed.com', '1651');
INSERT INTO user (last_name, first_name, email, password) VALUES('Garza', 'Martha', 'mgarza29@fastcompany.com', '2298');
INSERT INTO user (last_name, first_name, email, password) VALUES('George', 'Angela', 'ageorgew@slashdot.org', '8310');
INSERT INTO user (last_name, first_name, email, password) VALUES('George', 'Linda', 'lgeorge27@mtv.com', '4554');
INSERT INTO user (last_name, first_name, email, password) VALUES('Gilbert', 'Rose', 'rgilbert1c@java.com', '3359');
INSERT INTO user (last_name, first_name, email, password) VALUES('Gomez', 'Jacqueline', 'jgomeze@miitbeian.gov.cn', '4371');

INSERT INTO booking (user_id, rest_id, tabl_id, res_date) VALUES ((SELECT id FROM user WHERE id = '1'), (SELECT id FROM restaurant WHERE name = 'Enzos'), (SELECT id FROM tabl WHERE id = '1'), '2017-01-01');

