CREATE TABLE restaurant(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(16) NOT NULL,
  kitchen VARCHAR(16) NOT NULL,
  address VARCHAR(32) NOT NULL,
  info VARCHAR(100) NOT NULL
);

CREATE TABLE tabl(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    pax INTEGER NOT NULL,
    rest_id INTEGER NOT NULL
);

CREATE TABLE user(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(16),
  last_name VARCHAR(16),
  email VARCHAR(32),
  password VARCHAR(8)
);

CREATE TABLE booking(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  rest_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  tabl_id INTEGER NOT NULL,
  res_date DATE
);

ALTER TABLE tabl ADD FOREIGN KEY (rest_id) REFERENCES restaurant(id);
ALTER TABLE booking ADD FOREIGN KEY (rest_id) REFERENCES restaurant(id);
ALTER TABLE booking ADD FOREIGN KEY (user_id) REFERENCES user(id);
ALTER TABLE booking ADD FOREIGN KEY (tabl_id) REFERENCES tabl(id);
CREATE INDEX IDX_RES_DATE_ ON booking(res_date);
